FROM node:latest

ADD * /app/

RUN cd /app && npm install

ARG DISCORD_BOT_TOKEN
ARG RUNNER_ROLE_ID
ARG COMMENTATOR_ROLE_ID
ARG RUNNERS_CHANNEL_ID

ENV DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN
ENV RUNNER_ROLE_ID=$RUNNER_ROLE_ID
ENV COMMENTATOR_ROLE_ID=$COMMENTATOR_ROLE_ID
ENV RUNNERS_CHANNEL_ID=$RUNNERS_CHANNEL_ID

CMD cd /app && /usr/local/bin/node server.js
